### ISSUE TITLE
could you compile the new one thanks

### ISSUE THREAD

**Issue by formatme** [weaversam8/upterm-download-0.2.153#1]
could you compile the new one thanks

**Comment by weaversam8** [comment]
Currently, I'm not prepared to offer resources to build a new version. This was a one time effort in an attempt to support the issue railsware/upterm@800, which is the active issue attempting to build real windows support into upterm. That's the issue we need to be dedicating our resources to. I apologize, but this was a single example, not a long term project.

**Comment by formatme** [comment]
thanks
